createProject:
    path: /create-project
    controller: App\Controller\ProjectController::createProject
    methods: [POST]

getProjectInfo:
    path: /get-project-info
    controller: App\Controller\ProjectController::getProjectInfo
    methods: [POST]

updateProjectInfo:
    path: /update-project-info
    controller: App\Controller\ProjectController::updateProjectInfo
    methods: [POST]

removeProject:
    path: /remove-project
    controller: App\Controller\ProjectController::removeProject
    methods: [POST]

addPerk:
    path: /add-perk
    controller: App\Controller\PerkController::addPerk
    methods: [POST]

updatePerkInfo:
    path: /update-perk-info
    controller: App\Controller\PerkController::updatePerkInfo
    methods: [POST]

removePerk:
    path: /remove-perk
    controller: App\Controller\PerkController::removePerk
    methods: [POST]

getPerksInfo:
    path: /get-perks-info
    controller: App\Controller\PerkController::getPerksInfo
    methods: [POST]

getCategories:
    path: /get-categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]

getProjectsListing:
    path: /get-projects-listing
    controller: App\Controller\ProjectController::getProjectsListing
    methods: [POST]

