addProject:
    path: /add-project
    controller: App\Controller\ProjectController::addProject
    methods: [POST]

getCategories:
    path: /get-categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]
