addProject:
    path: /add-project
    controller: App\Controller\ProjectController::addProject
    methods: [POST]

addPerk:
    path: /add-perk
    controller: App\Controller\PerkController::addPerk
    methods: [POST]

getProject:
    path: /get-project
    controller: App\Controller\ProjectController::getProject
    methods: [GET]

getCategories:
    path: /get-categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]
