createProject:
    path: /create-project
    controller: App\Controller\ProjectController::createProject
    methods: [POST]

getProjectInfo:
    path: /get-project-info
    controller: App\Controller\ProjectController::getProjectInfo
    methods: [GET]

updateProjectInfo:
    path: /update-project-info
    controller: App\Controller\ProjectController::updateProjectInfo
    methods: [POST]

addPerk:
    path: /add-perk
    controller: App\Controller\PerkController::addPerk
    methods: [POST]

getCategories:
    path: /get-categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]
